### PR TITLE
Add new features.

### PR DESCRIPTION
**Pull request by hydra-bu**
Signed-off-by: youngman <shengquan.bu@iquantex.com>

#### What this PR does / why we need it:
1. Add oh-my-bash.
2. Modify install script.
3. Update README.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO] signed
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by hydra-bu** [comment]
hello sir, These script files fail the automatic inspection mechanism but do not affect the actual use of the function.

**Comment by Aisuko** [comment]
@spring-bu You are welcome. This is a draft PR and are you sure we can merge that?

**Comment by hydra-bu** [comment]
> @spring-bu You are welcome. This is a draft PR and are you sure we can merge that?

yes of course.

**Comment by Aisuko** [comment]
@spring-bu Thanks. Please make your original master branch up to date. And check the feature if it is not working well.

**Pull request merged**
